qa-include/app/favorites.php
qa-include/app/format.php
qa-include/app/mailing.php
qa-include/app/options.php
qa-include/app/recalc.php
qa-include/app/upload.php
qa-include/lang/qa-lang-main.php
qa-include/lang/qa-lang-options.php
qa-include/pages/admin/admin-categories.php
qa-include/pages/admin/admin-default.php
qa-include/pages/admin/admin-stats.php
qa-include/pages/categories.php
qa-include/pages/tags.php
qa-include/pages/user-profile.php
qa-include/pages/users.php
qa-include/plugins/qa-widget-activity-count.php
qa-plugin/wysiwyg-editor/qa-wysiwyg-editor.php
qa-theme/Snow/qa-theme.php
qa-theme/SnowFlat/inc/qam-snow-theme.php

Continuing with the discussion in #158.
Ok, so these are the numbers I've modified. I guess those are all. Also note this doesn't include a feature to allow all numbers to be translated because that would mean all numbers should go through this function and there are many constants (particularly, a lot of number ones used in, e.g., "1_year") that I have not included. Anyway, it is a first step towards that direction.
A related item to mention is that I noticed this construction
```php
$value == 1
? qa_lang_html_sub('main/1_value', '1', '1')
: qa_lang_html_sub('main/x_value', $value)
```
is repeated too often and I think it might be better to add some `qa_lang_html_sub_one_many($value, $langStringOne, $langStringMany)` function to reuse some code.
Regarding the "compacting" of numbers I've …

[Improvement - LOW] Improvements in how numbers are displayed

---

qa-include/util/string.php
qa-plugin/mouseover-layer/qa-mouseover-layer.php

Minor refactor of `qa_shorten_string_line`
Minor changes to the mouse-layer plugin
1. Fix #248 (text being cut twice)
1. Split presentation logic
1. Removed duplicated blanks, tabs, new lines, etc to compact the string

[Refactor] Minor changes to the mouse-layer plugin

---

qa-include/db/cache.php
qa-include/db/install.php
qa-include/db/metas.php
qa-include/db/options.php
qa-include/db/points.php
qa-include/db/post-create.php
qa-include/db/post-update.php
qa-include/db/users.php

As discussed in http://www.question2answer.org/qa/45016/ `REPLACE` syntax is considerably slower than the `INSERT..ON DUPLICATE KEY UPDATE` so changing all of them seems to be the way to go.

[Refactor] Turned all REPLACE statements into INSERT..ON DUPLICATE KEY UPDATE

---

qa-theme/SnowFlat/qa-styles.css

The `#level` field in the user profile takes the styling of the private message link to all the links inside, including the category-specific ones:
Alternatively, the whole "button styling" could be removed and keep them all as links.
More alternatively, the way of contacting a user should not be in the level field. It seems it ended up there just because there was some space available.

[Theme] Removed the link styling from the categories in the level user profile field

---

qa-include/lang/qa-lang-profile.php
qa-include/pages/message.php

It seems accessing a private message URL (http://yoursite.com/message/pupi1985) of a user who has not enabled private messages results in a "Page not found" error message. IMO, this could be OK.
However, considering the fact that emails sent from private messages have a "Reply" button it is possible to receive an email with a link to this page. If the original user disabled private messages from their profile after the email was sent and the recipient of the email tries to reply from the link in the email, they will get the "Page not found" error message. This might be confusing and might lead to think the original user has been deleted.
Reference: http://www.question2answer.org/qa/46582

[Refactor] Let user know why they can't send a private message to another user

---

qa-include/pages/question-post.php

After posting a comment to a question the comment anchor is wrong . This
commit fixes this issue with the correct anchor
fixed #266

[BugFix] - Correct url after posting a comment to the question 

---

qa-include/pages/ask.php

do not allow user to post the duplicate question once more time . It
checks the last 5 questions and compares with the current one . If any
of them appears to be same the user will be warned and the question will
not be posted
Fixes - #309

[BugFix]-Restrict the user to post duplicate questions

---

qa-include/util/external-users-wp.php

Q2A doesn't use `wp_registration_url` WP function for fetching registration URL so it bypasses `register_url` filter. This filter can be used for adding custom registration pages.
I added WordPress function `wp_registration_url` for fetching registration URL while still keeping compatibility with older WordPress (bellow 3.6) that do not have this function.

Replaced registration URL for WordPress integration

---

qa-include/app/users.php
qa-include/pages/account.php
qa-include/pages/login.php
qa-include/qa-base.php

hash_equals provides a timing attack safe string comparison for hashes

[security] use hash_equals to compare hashes

---

README.md
qa-config-example.php
qa-include/app/users.php
qa-include/qa-base.php
qa-include/qa-install.php
qa-include/util/external-users-joomla.php
qa-include/util/qa-joomla-helper.php

These changes implement out-of-the-box integration with Joomla!, in a similar vein to the existing Wordpress integration.
In addition to these changes, the Joomla! integration also requires a plugin to be installed into Joomla! (see https://github.com/SFWLtd/plg_q2a_integration). This plugin allows the Joomla! administrator to configure the Joomla! permissions that will grant different levels of access to Q2A.
Note that the installation instructions on the Joomla! plugin currently describe how to install it with a version of Q2A that does not contain the changes in this pull request. The changes here will allow those installation instructions to be dramatically simplified.

Out-of-the-box Joomla! integration.

---

qa-include/app/emails.php
qa-include/pages/feedback.php

If the email address user inputed has forced SPF check, the email will not be received by major ESPs unless it is put in `Reply-to` field instead of `From` field.

Change from / reply-to for feedback form

---

qa-include/app/options.php

When `$_SERVER['SCRIPT_NAME']` is at the root such as `/index.php` then calling `qa_default_option('site_url')` generates a double slash. This commit removes it.

Fix double slash in default site_url option

---

qa-theme/SnowFlat/qa-styles.css

It only applies to Firefox. It seems `word-break` is not standard.
Related to: http://www.question2answer.org/qa/54257?show=54631#c54631

Fix words falling off the edge of the answer container

---

qa-include/app/users-edit.php
qa-include/lang/qa-lang-misc.php
qa-include/lang/qa-lang-users.php
qa-include/pages/forgot.php
qa-include/pages/reset.php

I took some of the suggestions in #455 and tried to make the forgot password process a bit shorter. In this branch, the user should navigate to `/forgot` and input their username as they did before:
This will do 2 things: one would be to send the same first email as before (with a link to the reset password page containing the code and the shortcut link). The other would be to display a form to input only the code:
If the user inputs the code manually and clicks on the _Next step_ button, this will take them to the password confirmation page (which is still in the reset.php file)
If the user instead of manually writing the code, prefers to click the link in the email, then he will be sent to the password confirmation page directly.
Once the user inputs a valid password they will get …

Remove unnecessary step in password reset

---

qa-include/app/users-edit.php
qa-include/lang/qa-lang-emails.php

Just another awkward commit.
Imagine a user is using a Q2A mobile app. They request to change their e-mail address and the site requires e-mail confirmation. They open their mobile e-mail client. Tthe email they receive has a link which makes them open a 3rd app: the browser. The idea of the mobile app is not to depend on the browser but unless the user selectively copies the code from the URL they have no other option than opening the browser.
This way there is no dependency on the browser and it would be possible for the mobile app to ask the user to input the code manually, which can be easily copy/pasted.

Include confirmation code in confirmation email

---

qa-content/qa-admin.js
qa-include/ajax/version.php
qa-include/pages/admin/admin-default.php
qa-include/pages/admin/admin-plugins.php
qa-include/pages/admin/admin-stats.php

I know this might be a kind of political commit but it:
- Improves the look and feel of the number as the links are now rendered by the theme and not in an iframe
- Follows the `all development is taking place through GitHub` premise in the README
- Saves time when releasing a new Q2A version
- Decouples the need of getting both links updated before releasing which means more independance
- Slightly increases privacy :)

Fetch latest released Q2A version from GitHub itself

---

qa-include/app/post-update.php

I slightly change the documentation of `qa_question_set_selchildid` as it doesn't actually need all answers but just the affected ones at most.
Commit to blame: @8c4db57c71383cf679f0992311430843b4dff764
PS: I've just realized now single-line control structures require braces. Yay!

Fix a_unselect not being called when hiding selected answer

---

qa-include/app/users.php

There are many bots around and they generate a lot of information in the error log making it hard to browse. Besides, that information are not errors per se, but just the result of publishing a site in Internet. Maybe displaying them when in debug mode is a good option. Additionally, that could be set from an admin option, but most people won't understand what that is nor how to interpret the logs either. It might only be necessary in "development mode" which we don't have but debug performance is close enough :)

Do not log security form violations unless in debug mode

---

qa-include/pages/question-post.php

Fix for #417 
http://www.example.com/123/blah→bleh
First of all: that is not a valid URL so we can't blame PHP for just saying the truth :) Encoding the query string might be the most appropriate approach but probably unnecessary. Let's just make it valid in a quick way to see if it is a URL or not.

Fix unencoded URLs not being detected when closing questions

---

qa-content/qa-admin.js
qa-include/Q2A/Plugin/PluginManager.php
qa-include/app/admin.php
qa-include/db/install.php
qa-include/lang/qa-lang-admin.php
qa-include/pages/admin/admin-plugins.php
qa-include/qa-base.php

I think the subject says it all. There are a few things to bear in mind, though.
- The code is a bit dirty and undocumented (writing the doc takes almost the same time as developing this so I'm waiting for some feedback before doing that).
- Plugins that are disabled should not even register because if they do so they'd execute the `qa-plugin.php` code and the main idea is not to execute that file. This generates a possibly undesired behaviour when showing plugin specific options as the "options" link comes from executing the plugin's code.
- Additionally, some code had to be slightly reordered so that the `init_queries` function doesn't get called either.
- In order to avoid the object creation overhead in `qa_admin_plugin_directory_hash`, the `getHashesForPlugins` method could be made …

Add ability to disable plugins

---

qa-include/Q2A/Plugin/PluginManager.php
qa-include/pages/admin/admin-plugins.php
qa-include/qa-base.php
qa-tests/autoload.php

Summary of the changes
* Split the `qa_load_plugin_files()` function into the parsing of the metadata files and the loading the plugins themselves
* Moved the previous mentioned functions to the `PluginManager`
* Modified how overrides are loaded: instead of being added to the global `$qa_override_files` variable they are queued in `$qa_override_files_temp` as a delayed load
* Function `qa_load_override_files()` instead of loading all overrides from the global variable `$qa_override_files` it loads them from the temp one and also adds them to the original `$a_override_files` global variable just to keep backwards compatibility (probably unnecessary)
* The plugin load (including loading the overrides) happen before and after connecting to the database
* Added `load_order` to the …

Add ability to load plugins after and before connecting to the DB

---

qa-include/vendor/PHPMailer/class.phpmailer.php
qa-include/vendor/PHPMailer/class.smtp.php

Updated PHPMailer to v5.2.23  (from v5.2.14) stable version. There are some security fixes in this version. Please see https://github.com/PHPMailer/PHPMailer
These two files are taken from above repository. 
**Security notices relating to PHPMailer**
https://github.com/PHPMailer/PHPMailer/blob/master/SECURITY.md
Taken from above file....
PHPMailer versions prior to 5.2.22 (released January 9th 2017) have a local file disclosure vulnerability, CVE-2017-5223. If content passed into msgHTML() is sourced from unfiltered user input, relative paths can map to absolute local file paths and added as attachments. Also note that addAttachment (just like file_get_contents, passthru, unlink, etc) should not be passed user-sourced params either! Reported by Yongxiang Li of Asiasecurity.
PHPMailer …

Updated PHPMailer to v5.2.23 (from v5.2.14)

---

.travis.yml

Travis CI failing for Q2A v18, issue with php 5.3, see below link for more detail
http://question2answer.org/qa/58152/travis-ci-failing-for-q2a-v18-issue-with-php-5-3

Fixed php 5.3 Travis CI fail issue

---

qa-include/app/format.php
qa-include/lang/qa-lang-main.php

Just passing by and saw the simple issue #536 so I thought of sending a keep-alive.
I suggest deprecating `vote_disabled_my_x the same` the same as `vote_disabled_hidden_x`.

Unify own post message language string

---

qa-include/app/admin.php
qa-include/pages/admin/admin-default.php

At least happening in PHP 7. Applied the old-style fix because it is deprecated code.

Fix a few warnings generated by reading contents from non-existent files

---

qa-include/db/install.php
qa-include/qa-db.php

To reproduce this create a new schema. Add a custom table. Start installing Q2A. You'll eventually see:
The fix just filters based on the Q2A table prefix. It also takes that into account when upgrading as it doesn't make any sense to block non-Q2A tables while doing so.
Note plugins should still receive the full table list (not the filtered one). Otherwise, this won't be backwards compatible.
This makes me wonder whether plugins should use or not the Q2A table prefix in their table names. I used to think they shouldn't in order to avoid "namespaces" issues with the core. However, other issues might still arise if there are 2 sites sharing the same schema using different prefix that have the same plugin installed. That plugin would try to create the same table twice.
I'm even thinking …

Fix table counts during Q2A installation

---

qa-include/app/post-update.php

Steps to reproduce
0. Prepare points so that you get X points per comment upvote
1. Add an answer
2. Upvote the answer
3. Turn answer to comment
You should have X less points as the points for the newly created comment are not taken into account.

Fix points recalculation when turning answers to comments

---

qa-include/db/hotness.php
qa-include/db/selects.php

There were a few missing ones. I haven't tested this much but the fix should be quite mechanical: if the ordering didn't originally care, then getting any of them should be the same.

Fix non-ANSI group-by queries

---

qa-include/vendor/htmLawed.php

Bug Fix:
1.2.4.1 - 12 September 2017. Corrects a function re-declaration bug introduced in version 1.2.4
Above file taken from http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/

Updated htmLawed to v1.2.4.1 - 12 September 2017.

---

qa-include/qa-base.php

Check these 3 lines: https://github.com/q2a/question2answer/blob/19be025e12d3d5c8bdfbfcaec2b39df395a4be00/qa-include/qa-page.php#L34-L36
You can see the `after_db_init` plugins don't get the `init_page` method called. This arguably makes sense: on one hand there should be a method called as early as possible (and it even makes sense for it to be called before the db connects) but on the other we should not remove the ability for `after_db_init` `process`es to also execute early in the bootstrap process.
The quick fix would be to try to load the `process` modules immediately after they have been registered. This can be done just by making a call to `qa_report_process_stage()` right after the modules are loaded. As at this point all plugins are fully loaded it could make sense to call it …

Load process modules as early as possible for after_db_init plugins

---

qa-include/app/users.php

Move function to outside the if/else external users statement as Gravatar can be used in both worlds. Currently, the issue is it is being fired from the `external-users.php` file, `qa_avatar_html_from_userid()` function.

Fix qa_get_gravatar_url() function not found when using WordPress

---

qa-include/app/users.php
qa-include/db/selects.php

Assuming a user is overriding the `QA_MYSQL_USERS_PREFIX` then there are different sites each with its own `^userpoints` table. The thing is when a site creates a user then that site (and only that site) executes this line: https://github.com/q2a/question2answer/blob/cfec3c0155817ffba49b06435a05ebb3ef9859a1/qa-include/app/users-edit.php#L192
As sites are independent I don't think making a site communicate to each other the creation of the user would make any sense.
That means having to cope with the fact that there might be records in the `^users` table that are not in the `^userpoints` table. I don't think this is a big deal.
The current issue can be seen when listing top users. The query uses an `INNER JOIN` against the `userpoints` table which immediately removes all non present users. …

Fix some scenarios where ^userpoints records are not present and generate issues

---

qa-include/qa-theme-base.php

Seems to be working based on this comment: http://www.question2answer.org/qa/62349/malware-detected-in-q2a-code?show=62404#c62404

Simplify hidden HTML and avoid its detection as malware

---

qa-include/app/post-create.php
qa-include/app/post-update.php
qa-include/plugins/qa-search-basic.php

To see this bug create a question with 2 new tags. Delete the question. Set the tag list length to 2. Navigate to the /tags page. Go to the last page. It should appear blank.
The cached tag count is not being updated on question removal.
I also removed the cache update away from the basic search plugin because the cache should be updated regardless of the search plugin that is being used.

Update cached tag count when deleting posts

---

qa-include/app/format.php

Technically, the most appropriate check would be: `isset()`, `is_array()`, `!empty()`. However, as we know it is an array or it is not set we can remove the `is_array()` check. Furthermore, I think it is always set... but maybe I'm missing something.

Fix another PHP 7.2 count warning

---

qa-theme/SnowFlat/qa-theme.php

On mobile search box looks confusing if it is for search or ask a question so added this placeholder.
After adding placeholder it looks like this.

Added placeholder "Search..." for search box

---

qa-include/app/users.php

The function is returning too early so anonymous users don't get to be assigned a default image in question lists. The default image should be displayed regardless of the user being anonymous or not. The link to the user profile should not be displayed for anonymous users.

Fix anonymous user images not being displayed

---

qa-include/app/page.php

This way plugins can rely on jQuery in that point. I don't think this should break any currently existing plugins as currently the plugins that try to use jQuery in that point would not be able to do so, which means the order would not matter to them.

Add jquery and other dependencies before addon dependencies

---

qa-plugin/wysiwyg-editor/ckeditor/config.js
qa-plugin/wysiwyg-editor/qa-wysiwyg-editor.php

Some CKEditor configurations are essential for Q2A to interact with CKEditor. Those configurations should not be stored inside the ckeditor directory as it might be overriden by the instructions in the `CUSTOMIZE.md` file (which I believe they're OK!).
The rest of the configurations in the config.js file could still be moved the thing is that then the opposite will happen: Q2A will override them. That's why I think if they are essential, then they should not be overridable. Otherwise, they should.

Remove essential CKEditor configuration from config.js file

---

qa-include/app/mailing.php
qa-include/db/users.php

It could be done by filtering users out from the query itself. However, the counting of users would have to run using a non-indexed query. I think that's why users not willing to receive the email were filtered out in a similar way in the first place.

Avoid sending emails to blocked and unapproved users

---

qa-config-example.php
qa-include/Q2A/Util/Usage.php
qa-include/pages/admin/admin-userfields.php
qa-include/pages/question-post.php
qa-include/pages/user-profile.php
qa-include/plugins/qa-widget-ask-box.php
qa-plugin/facebook-login/qa-facebook-login.php
qa-plugin/mouseover-layer/qa-mouseover-layer.php

Just for reference, phpcs 3.3.1 is throwing all these:
```
qa-include/pages/admin/admin-userfields.php:102:39: error - Blank line found at start of control structure
qa-include/pages/question-post.php:811:15: error - Blank line found at start of control structure
qa-include/pages/user-profile.php:91:7: error - Blank line found at start of control structure
qa-include/Q2A/Util/Usage.php:112:1: error - Line indented incorrectly; expected 2 tabs, found 0
qa-include/Q2A/Util/Usage.php:158:1: error - Line indented incorrectly; expected at least 2 tabs, found 0
qa-include/Q2A/Util/Usage.php:193:1: error - Line indented incorrectly; expected at least 2 tabs, found 0
qa-include/plugins/qa-widget-ask-box.php:45:1: error - Line indented incorrectly; expected 2 tabs, found 0 …
```

Fix many phpcs complaints

---

qa-include/ajax/answer.php
qa-include/app/format.php
qa-include/app/post-update.php
qa-include/app/q-list.php
qa-include/pages/question-view.php
qa-include/qa-feed.php

It seems the core doesn't properly handle the `do_close_on_select` setting. It seems the rules were the only ones that were taking care of that setting:
https://github.com/q2a/question2answer/blob/1f39ae44adf42c83042be631e39373893a3ec969/qa-include/pages/question-view.php#L121
The rest of the core only considers a non-null `closedbyid` as the indicator of a closed question. I can think of two options to fix this:
1. Allow answer ids in the `closedbyid` so that the selected answer takes the place of the note or question duplicate. This approach seems to be the best one but is a bit non-backwards compatible as now questions can be closed by answers. Also SQL queries that consider closed questions as non-null `closedbyid` would be accurate (note they are not accurate currently).
1. Change …

Fix closed questions by selected answer not displayed as closed

---

qa-include/app/users-edit.php
qa-include/app/users.php
qa-include/db/users.php
qa-include/pages/user-profile.php
qa-include/qa-db.php

This is not just saving a few SQL queries but also saving some additional queries that addons may run.
Also I'm adding the `qa_db_query_sub_params()` function which is much more flexible than its sibling `qa_db_query_sub()`. I noticed that I ended up needing it in most of my plugins.
#666 :smiling_imp:

Remove some unnecessary SQL queries

---

qa-include/pages/question-view.php

This is how it looks in 1.8.2:
Voting should just be removed

Fix voting on follow-on questions

---

qa-include/lang/qa-lang-admin.php

This key isn't used since f394a34c54b938218e8bb92549ae3a1f480e6f8a . Removing
it ensures translators don't bother translating it for nothing

Rm lang key "caching_dir_public"

---

qa-include/app/post-update.php

Steps to reproduce:
1. Disable `do_close_on_select`
2. Select an answer
3. The question is displayed as `reopened`
> If debugging is the process of removing bugs, then programming must be the process of putting them in

Fix selection of answers trying to close questions

---

qa-include/pages/admin/admin-categories.php

I think it is necessary to have these events to make plugins be able to set category meta right after the category is created and/or for eventlog

Category add and edit event

---

qa-include/pages/user-profile.php

This is useful whenever some action needs to be taken before deleting the user. For example, performing some action on their votes. Once the user is removed, it is not possible to access that information.
Changes to the events documentation have been added here: https://github.com/q2a/q2a.github.io/pull/25

Fire u_delete_before event before deleting a user

---

qa-include/db/users.php

alongside their own bookmarked users; when deleting users. It'll save some database space.

Remove bookmark entries about deleted users

---

qa-include/qa-base.php

Due to the design of the file_get_contents function, sometimes getting external content will be very slow. You should use curl instead if possible. For details, see here: https://stackoverflow.com/questions/3629504/php-file-get-contents-very- slow-when-using-full-url

use curl instead of file_get_contents

---

qa-include/app/users.php

According to Mozilla best-practices (see https://observatory.mozilla.org
and https://infosec.mozilla.org/guidelines/web_security#cookies )
session cookies should be created with the HttpOnly flag. This prevents
XSS vulnerabilities.
This PHPSESSID cookie is still sent over ajax calls (it just prevents JS to
access it) so it does not break any usage

Increase security by setting the httpOnly flag to session cookie

---

qa-include/app/captcha.php
qa-include/pages/account.php
qa-include/pages/admin/admin-categories.php
qa-include/pages/admin/admin-default.php
qa-include/pages/admin/admin-pages.php
qa-include/pages/admin/admin-userfields.php
qa-include/pages/admin/admin-usertitles.php
qa-include/pages/ask.php
qa-include/pages/feedback.php
qa-include/pages/forgot.php
qa-include/pages/login.php
qa-include/pages/message.php
qa-include/pages/question-post.php
qa-include/pages/question-view.php
qa-include/pages/question.php
qa-include/pages/register.php
qa-include/pages/user-profile.php
qa-include/pages/user-wall.php

I've removed many usages of the @ sign and initialized the `@errors` variable in all pages I noticed it was used.
I have not removed all @ signs, but this should get the code one step closer to that.
This PR should also fix #888.

Fix many issues regarding $errors variable and @ character

---

qa-include/app/format.php
qa-include/pages/search.php

The main issue is that `QA_MAX_LIMIT_START` is limiting the amount of pages displayed when using the Q2A pagination. This is fine for most core features, but when writing plugins, it might be important to override this limitation. Of course it is possible to copy/paste the function and tweak it, but that's just not great.
Instead of adding another parameter to the huge function, I thought that one parameter could be re-purposed. The `$hasmore` parameter is there to add an ellipsis at the end of the pages. At first sight, it seems related to the limit imposed by `QA_MAX_LIMIT_START`: if the limit is reached and there are more results that are not being displayed, at least show the ellipsis to tell the user there are more stuff.
However, that is not correct. If it was, then why send it as a …

Allow pagination of element lists that exceed QA_MAX_LIMIT_START

---

qa-include/qa-base.php

Finally, I got access to a link showing this error. I believe I've cracked it. It seems people copy/paste other answers. If they copy the part of the answer that includes microdata, then the microdata is also copied. So when they paste the content, they also paste the microdata from other original answer.
This results in an answer having the "text" attribute of its own and also a nested "text" attribute from the original answer. This should be fixed by just disallowing all microdata tags.

Fix duplicated mainEntity.suggestedAnswer.text microdata error

---

qa-include/qa-image.php

This should fix #919. It takes into account the `blobid` column is `bigint` in MySQL and cannot be converted to a PHP integer

Handle invalid blob IDs when requesting images

---

qa-include/pages/user-profile.php

Fetching the user account data early will return the userid of the profile's users. Doing this separately will avoid several lookups in the ^users table to turn the handle to a userid.
The only downside is that, for far away servers, the performance gain might be loss because of the latency of running two queries. I believe these affected users should be much less than 1%. Furthermore, if the result for them is having slower times than before, then using Q2A for those users was already a pretty bad experience.

Avoid joining with users table to get userid several times on user profile page

---

qa-include/ajax/answer.php
qa-include/ajax/comment.php
qa-include/app/users.php
qa-include/pages/ask.php
qa-include/pages/feedback.php
qa-include/pages/question.php

When the "Use captcha for anonymous posts" setting is unchecked, captcha is not showing on feedback form, as it is treated as an anonymous post.
I could just fix this by checking if the user is anonymous and, if it is, just avoid calling the `qa_user_captcha_reason()`. The thing is that I would be getting part of the logic from that function out of the function. So I'd rather keep the logic (the `if` statement) in the function and just send the function the actual data to process it.
In other words, I think it is better to change the signature from:
```php
function qa_user_captcha_reason($userlevel = null)
```
to:
```php
function qa_user_captcha_reason($userlevel = null, $showCaptchaIfAnonymous = true)
```
This way the
```php
if (qa_opt('captcha_on_anon_post') && !isset($userid))
``` …

Fix captcha on feedback page not being shown for anonymous users
