qa-include/Q2A/Util/Usage.php
While trying to debug some data I realized it was quite harder to read and compare using a string. Maybe a table would help.
=> [Improvement - LOW] Turned the debug output into a table

qa-include/app/post-update.php, qa-include/pages/admin/admin-default.php, qa-include/pages/register.php, qa-plugin/facebook-login/qa-facebook-login-page.php, qa-plugin/xml-sitemap/qa-xml-sitemap.php
I'm also including minor changes and a bugfix to this pull request to avoid creating too many simple pull requests
=> [Refactor] Moved the TOS right before the register button

qa-plugin/recaptcha-captcha/qa-recaptcha-captcha.php, qa-plugin/recaptcha-captcha/recaptchalib.php
fixed #300 
This is an alternate solution for https://github.com/q2a/question2answer/pull/301
=> [BugFix] - fixed dependency for allow_url_fopen configuration

qa-theme/Candy/qa-styles.css, qa-theme/Classic/qa-styles.css, qa-theme/Snow/qa-styles.css, qa-theme/SnowFlat/qa-styles.css
=> [Improvement] - Content focus when a answer or a comment is opened (Fixes #234)

qa-include/ajax/notice.php, qa-include/app/cookies.php, qa-include/app/users.php, qa-include/qa-page.php
See https://github.com/q2a/question2answer/issues/358
=> set HttpOnly flag for cookies

qa-theme/SnowFlat/qa-styles.css, qa-theme/SnowFlat/qa-theme.php
=> Block layout for users and tags page

qa-include/db/recalc.php
https://github.com/q2a/question2answer/issues/370
=> Fix issue 370

qa-include/qa-db.php
Support for WordPress MySQL alternate port : https://codex.wordpress.org/Editing_wp-config.php#MySQL_Alternate_Port
=> Support wordpress host port

qa-include/app/emails.php
This can be very helpful when trying to figure out why emails aren't being sent.
=> Log any email sending errors

qa-plugin/recaptcha-captcha/qa-recaptcha-captcha.php
Google changed name of reCAPTCHA key so updated file.
=> Changed name of reCAPTCHA key so updated file.

qa-include/plugins/qa-filter-basic.php
=> A few filter-basic fixes

qa-include/db/install.php, qa-include/db/post-update.php, qa-include/db/users.php, qa-include/pages/admin/admin-default.php, qa-include/pages/admin/admin-plugins.php, qa-include/pages/admin/admin-recalc.php, qa-include/pages/categories.php, qa-include/pages/forgot.php, qa-include/qa-base.php, qa-include/qa-check-lang.php, qa-include/qa-db.php, qa-plugin/event-logger/qa-event-logger.php, qa-plugin/wysiwyg-editor/qa-wysiwyg-editor.php, qa-plugin/xml-sitemap/qa-xml-sitemap.php, qa-theme/Candy/qa-styles.css, qa-theme/Classic/qa-styles.css, qa-theme/Snow/qa-styles.css, qa-theme/SnowFlat/qa-styles.css
This is just a PR with many independent and almost useless commits just for cherry-picking.
=> Some minor changes

qa-include/ajax/asktitle.php
https://github.com/q2a/question2answer/issues/440
=> Fix of issue 440

qa-include/app/format.php, qa-include/app/users.php
I'm in a hurry so I haven't tested this one much.
* Created function `qa_get_avatar_blob_url` that returns a link to a locally stored avatar
* Created function `qa_get_gravatar_url` that returns a link to a Gravatar
* Created function `qa_get_user_avatar_source` that returns the source that will be used for the given parameters
* Created function `qa_get_user_avatar_url` that returns a link to an avatar, regardless of the source (this is actually the motivation for the PR)
Finally
* Updated `qa_get_avatar_blob_html` to call `qa_get_avatar_blob_url`
* Updated `qa_get_gravatar_html` to call `qa_get_gravatar_url`
Ref: http://www.question2answer.org/qa/32982
=> Improve avatar handling API

qa-include/app/format.php, qa-include/db/install.php
**Add default value for permit field in userfields initialization**
For some reason it was left null.
Slightly refactored the code too (hopefully making it easier to read).
**Make selects react on changing events rather than click events**
=> Some more minor changes

qa-plugin/facebook-login/base_facebook.php
@Scott, @pupi1985
This fix is written and verified by http://question2answer.org/qa/user/Dan+D. in below thread http://question2answer.org/qa/56966/facebook-login-stopped-working-its-not-even-working-your-site?show=56992#a56992
also see https://github.com/q2a/question2answer/issues/510
I'm just submitting code changes.
Please check line no 593 for currentUrl. 
Thanks to Q2A user Dan D, and Github users valan, iamdand, cksagherian for this patch.
=> Facebook login issue #510

README.md
Used ref from http://www.question2answer.org/sites.php
=> Updated readme for sites info

README.md
Pointed to correct build status png file.
=> Updated for Travis CI links

qa-include/app/format.php, qa-include/lang/qa-lang-main.php
renamed variable vote_disabled_hidden to vote_disabled_hidden_post, in sync with commit by pupi1985.
https://github.com/q2a/question2answer/pull/537
=> Renamed variable, in sync with commit by pupi1985

qa-theme/SnowFlat/qa-styles-rtl.css
Solution provided by fara, I verified fix on test site and it is working fine for RTL layout.
https://github.com/q2a/question2answer/issues/550
=> Fix for #550, RTL layout vote disply issue.

qa-include/pages/unsubscribe.php
Success message for successful unsubscribe - instead error
=> Success message for successful unsubscribe

qa-plugin/wysiwyg-editor/ckeditor/config.js
These buttons are just showing and not doing anything.
https://github.com/ckeditor/ckeditor-dev/issues/595
=> Paste/Paste isn't working in ckEditor

qa-include/lang/qa-lang-admin.php
https://github.com/q2a/question2answer/pull/598
=> pull 598 (2 part)

qa-include/app/options.php, qa-include/plugins/qa-filter-basic.php, qa-include/plugins/qa-layer-voters-flaggers.php, qa-plugin/wysiwyg-editor/qa-wysiwyg-editor.php, qa-plugin/xml-sitemap/qa-xml-sitemap.php
There are quite a lot more but it is not clear to me it what version they will be removed. This ones state the version or are clearly too old (Q2A v1.3).
=> Remove some deprecation messages

qa-include/app/format.php, qa-include/pages/account.php, qa-include/pages/feedback.php, qa-include/pages/forgot.php, qa-include/pages/login.php, qa-include/pages/register.php, qa-include/pages/user-profile.php, qa-include/qa-install.php, qa-include/qa-theme-base.php, qa-theme/Candy/qa-styles.css, qa-theme/Classic/qa-styles.css, qa-theme/Snow/qa-styles.css, qa-theme/Snow/qa-theme.php, qa-theme/SnowFlat/qa-styles.css, qa-theme/SnowFlat/qa-theme.php
=> Add email field type to forms

qa-plugin/wysiwyg-editor/qa-wysiwyg-upload.php
This also fixes the no-permission check not properly done
=> Refactor WYSIWYG file upload

qa-include/pages/question-view.php
=> Allow closed and hidden questions to be deleted with one click

qa-include/app/emails.php
=> Add ^site_url as a fixed substitution placeholder when sending email notifications

qa-include/ajax/answer.php, qa-include/app/format.php, qa-include/app/posts.php, qa-include/app/q-list.php, qa-include/app/users.php, qa-include/pages/question-view.php, qa-include/qa-feed.php
I'm also adding the @ since tag to a couple of the latest functions added. That would help plugin developers determine the appropriate minimum supported version of their plugins
=>  Extract closed question check into own function

qa-include/app/format.php
=> Fix negative upvoteCount wrongly displayed

qa-include/app/votes.php
=> Prevent duplicated vote events

qa-config-example.php
It did reference a file that did not exist anymore.
This here should work now.
=> Fix wrong file reference in config file

qa-include/pages/admin/admin-categories.php
Fix #898 . More `@` operator issues
=> Fix #898: error while adding categories in PHP 8

qa-include/pages/question.php
E.G.:
> Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/q2a/qa-include/app/captcha.php on line 85
=> Fix several captcha initialization issues
